// file to load features (AND MAYBYE LANGUAGES)
module.exports = {
    GET_PROJECT_PATH: 'GET_PROJECT_PATH',
    RECEIVED_PROJECT_PATH: 'RECEIVED_PROJECT_PATH', 
    SEND_SAVE_FILE_SIGNAL: 'SEND_SAVE_FILE_SIGNAL',
    RECEIVED_SAVE_FILE_SIGNAL: 'RECEIVED_SAVE_FILE_SIGNAL'
}




